instruments/urls.py
from django.urls import path, re_path
from . import views
#from .views import CreateInstrumentWizard      
from .forms import InstrumentModelCreateByInstTypeForm, DigitalLevelCreateForm, StaffCreateForm
from staffcalibration.forms import StaffCalibrationRecordFormOnTheGo

# url links below
app_name = 'instruments'

STAFFFORM = [
                ("inst_staff_form", StaffCreateForm),
                ("inst_staff_record_form", StaffCalibrationRecordFormOnTheGo),
                ] 

staff_creation_wizard = views.StaffCreationWizard.as_view(STAFFFORM, 
                            condition_dict={'inst_staff_record_form': views.show_calibrated_form_condition},
                            url_name = 'instruments:sstep')


urlpatterns = [
    path('', views.instruments_home, name = 'home'),
    # path('', views.instruments_levelling, name = 'home'),
    # Make & Models
    path('inst_make_create/', views.inst_make_create, name = 'inst_make_create'),
    path('inst_model_create/', views.inst_model_create, name = 'inst_model_create'),
    path('inst_model_createby_inst_type/<str:inst_type>/', views.inst_model_createby_inst_type, name = 'inst_model_createby_inst_type'),
    
    #EDMs
    path('inst_edm_create/', views.EDMCreateView.as_view(), name = 'edm_inst_create'),
    path('inst_edm_spec_create/', views.inst_edm_spec_create, name = 'inst_edm_spec_create'),
    path('inst_edm/<id>', views.inst_edm_detail, name = 'inst_edm_detail'),

    # Prisms
    path('inst_prism_create/', views.PrismCreateView.as_view(), name = 'prism_inst_create'),
    path('inst_prism_spec_create/', views.inst_prism_spec_create, name = 'inst_prism_spec_create'),
    # path('inst_spec_create/', views.inst_spec_create, name = 'inst_spec_create'),
    # path('inst_edm/<id>', views.inst_edm_detail, name = 'inst_edm_detail'),

    #Mets
    path('inst_mets_create/', views.MetsCreateView.as_view(), name = 'mets_inst_create'),
    path('inst_mets_spec_create/', views.inst_mets_spec_create, name = 'inst_mets_spec_create'),

    # Levelling staves
    path('inst_staff/<id>', views.inst_staff_detail, name = 'inst_staff_detail'),
    path('inst_staff_update/<id>/', views.inst_staff_update, name = 'inst_staff_update'),

    # Digital Level
    path('inst_level_create/', views.DigitalLevelCreateView.as_view(), name='inst_level_create'),
    path('inst_level_create_popup/', views.inst_level_create_popup, name = 'inst_level_create_popup'),
    path('inst_level/<id>', views.inst_level_detail, name = 'inst_level_detail'),
    path('inst_level_update/<id>/', views.inst_level_update, name = 'inst_level_update'),

    # Staves
    re_path(r'^inst_staff_create/(?P<step>.+)/$', staff_creation_wizard, name='sstep'),
    path('inst_staff_create/', staff_creation_wizard, name='inst_staff_create'),


    path('<id>/inst_model_update/', views.inst_model_update, name = 'inst_model_update'),
    path('<id>/inst_make_update/', views.inst_make_update, name = 'inst_make_update'),
]

instruments/models.py
#instruments
import uuid
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.core.validators  import MaxValueValidator, MinValueValidator, DecimalValidator, MinLengthValidator
from django.conf import settings
# Create your models here.
User = settings.AUTH_USER_MODEL
from accounts.models import CustomUser
from accounts.models import Company
from calibrationsites.models import CalibrationSite
#####################################################################
########################## SURVEY INSTRUMENTS #######################
#####################################################################
# class InstrumentType(models.Model):
#     name = models.CharField(max_length=25,help_text="e.g., Digital Level, EDM", unique=True)

class InstrumentMake(models.Model):
    make = models.CharField(max_length=25, validators=[MinLengthValidator(4)], help_text="e.g., LEICA, TRIMBLE, SOKKIA", unique=True)
    make_abbrev = models.CharField(max_length=4, validators=[MinLengthValidator(3)], help_text="e.g., LEI, TRIM, SOKK", unique=True, verbose_name = 'Abbreviation')
        
    def __str__(self):
        return self.make

class InstrumentModel(models.Model):
    inst_types = (
                ( None, 'Select one of the following'),
                ('edm','Total Station EDM'),
                ('prism','Prism'),
                ('level','Digital Level'),
                ('staff','Barcoded Staff'),
                ('baro','Barometer'),
                ('thermo','Themometer'),
                ('hygro','Hygrometer'),
                ('psy','Psychrometer'),
                ('others','Others'),)
					        
    inst_type = models.CharField(max_length=6,
                 choices=inst_types,
                 verbose_name= 'instrument type',
                 null = True)
    make = models.ForeignKey(InstrumentMake, on_delete = models.CASCADE, null = True)
    model = models.CharField(max_length=25, validators=[MinLengthValidator(3)], help_text="e.g., LS15, DNA03, TS30, S9, SX12, GT-1200/600")
    
    class Meta:
        ordering = ['inst_type','make','model']
        unique_together = ('inst_type','make','model')
    
    def __str__(self):
        return f'{self.model} ({self.inst_type})'
        # return f'{self.make} - {self.model}({self.inst_type})'
#####################################################################
########################## LEVELING INSTRUMENTS #####################
#####################################################################
class DigitalLevel(models.Model):
    # user = models.ForeignKey(CustomUser, on_delete = models.SET_NULL, null = True, blank = True)
    level_owner = models.ForeignKey(Company, on_delete = models.SET_NULL, null = True)
    level_number = models.CharField(max_length=15, validators=[MinLengthValidator(4)], 
                                    help_text="Enter the instrument number")
    level_model = models.ForeignKey(InstrumentModel, 
                                    limit_choices_to={'inst_type__exact': 'level'}, 
                                    on_delete = models.CASCADE, null = True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    modified_on = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ['level_number','level_model']
        unique_together = ['level_number', 'level_owner']
        
    def get_absolute_url(self):
        return reverse('instruments:inst_level_update', args=[str(self.id)])

    def __str__(self):
        return f'{self.level_number} {self.level_model}'

class Staff(models.Model):
    # user = models.ForeignKey(CustomUser, on_delete = models.SET_NULL, null = True, blank = True)
    staff_model = models.ForeignKey(InstrumentModel, 
                                    limit_choices_to={'inst_type__exact': 'staff'}, 
                                    on_delete = models.CASCADE, null = True)
    staff_owner = models.ForeignKey(Company, on_delete = models.SET_NULL, null = True)
    staff_number = models.CharField(max_length=15, validators=[MinLengthValidator(4)],
                                    help_text="Enter the instrument number")
    staff_types = (
                ( None, 'Select one of the following'),
                ('invar','Invar'),
                ('fiberglass','Fiber glass'),
                ('wood','Wood'),
                ('aluminium','Aluminium'),
                ('steel','Steel'),
				('epoxy','Carbon/epoxy'),
				('e_glass','E-glass'),
				('s2_glass','S2-glass'),)
					        
    staff_type = models.CharField(max_length=10,
                 choices=staff_types)

    staff_length = models.FloatField(
                                    validators = [MinValueValidator(1.0), MaxValueValidator(5.0)],
                                    help_text="Staff length in meters",
                                    verbose_name = "Staff length (in metres)")
    thermal_coefficient =  models.FloatField(
                                    null=True,
                                    validators = [MinValueValidator(-100), MaxValueValidator(100)],
                                    help_text="Coefficient of expansion in ppm units- e.g., Fibreglass: 10.0, Carbon: 3.0",
                                    verbose_name = "CoE (in ppm)")
    
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    modified_on = models.DateTimeField(auto_now=True, null=True)
    
    class Meta:
        unique_together = ['staff_number', 'staff_owner']
        ordering= ['staff_number']

    def __str__(self):
        return f'{self.staff_number} - {self.staff_type}'
        # return f'{self.staff_number} {self.staff_model}'
    
    def get_absolute_url(self):
        return reverse('instruments:inst_staff_update', args=[str(self.id)])
#####################################################################
############################ EDM INSTRUMENTS ########################
#####################################################################
class EDM_Specification(models.Model):
    edm_owner = models.ForeignKey(Company, on_delete = models.PROTECT, verbose_name = 'EDM owner')
    edm_model = models.ForeignKey(InstrumentModel,
                                  limit_choices_to={'inst_type__exact': 'edm'},
                                  on_delete = models.PROTECT, 
                                    verbose_name = 'EDM model')
    edm_types = (
        ('ph','Phase'),
        ('pu','Pulse'),
    )
    edm_type = models.CharField(
        max_length=2,
        choices=edm_types,
        default='ph',
        help_text='Instrument measurement type',
        verbose_name = 'EDM type'
    )
    manu_unc_const = models.FloatField(
        validators = [MinValueValidator(0.0), MaxValueValidator(10.0)],
        help_text="Accuracy = 1mm ± 1.5ppm, Uncertainty Constant = 1",
        verbose_name= 'manufacturers uncertainty constant')
    manu_unc_ppm = models.FloatField(
        validators = [MinValueValidator(0.0), MaxValueValidator(10.0)],
        help_text="Accuracy = 1mm ± 1.5ppm, Uncertainty ppm = 1.5",
        verbose_name= 'manufacturers parts per million uncertainty')
    manu_unc_k = models.FloatField(
        validators = [MinValueValidator(1.0), MaxValueValidator(5.0)],
        help_text="Coverage factor at 95% Confidence Level eg. 2.0",
        default = 2.0,
        verbose_name= 'manufacturers uncertainty coverage factor')
    
    unit_length = models.FloatField(
        validators = [MinValueValidator(0.0), MaxValueValidator(30.0)],
        help_text="Unit Length (m)")
    frequency = models.FloatField(
        validators = [MinValueValidator(1), MaxValueValidator(100000000)],
        help_text="Frequency (Hz)")
    carrier_wavelength = models.FloatField(
        validators = [MinValueValidator(1), MaxValueValidator(1000)],
        help_text="Carrier Wavelength (nm)")
    manu_ref_refrac_index = models.FloatField(
        validators = [MinValueValidator(0.000000000), MaxValueValidator(2.000000000)],
        help_text="Manufacturers reference refractive index",
        verbose_name= 'Manufacturers reference refractive index')
    measurement_increments = models.DecimalField(
        max_digits=7, decimal_places=6,
        help_text="Resolution of the measurement eg. 0.01")
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    modified_on = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ['edm_model']
        unique_together = ('edm_model','edm_owner')

    def get_absolute_url(self):
        return reverse('edm_model_calibrations:edm-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.edm_model.make} {self.edm_model.model} ({self.edm_owner.company_abbrev})'
############################################################################################
def get_upload_to_edm_photos(instance, filename):
    modified_date = instance.modified_on.strftime('%Y%m%d')
    filename = filename.split('\\')[-1]
    return 'Instruments/Photos/%s/%s/%s/%s' % (instance.edm_specs.edm_owner.company_abbrev, instance.edm_number, modified_date, filename)

class EDM_Inst (models.Model):
    edm_number = models.CharField(max_length=15, 
                                  help_text="Enter the instrument serial number / unique ID",
                                  verbose_name = 'EDM Number')
    edm_custodian = models.ForeignKey(CustomUser,
                                      null = True,
                                      blank = True,
                                      on_delete = models.SET_NULL,
                                      help_text="Name of instrument custodian",
                                      verbose_name = "EDM Custodian")

instruments/templates/instruments/inst_level_create_form.html
{% extends 'base_generic.html' %}
{% load i18n %}
{% load static %}

{% block content %} 

<article class="post">
    <!-- <div class="post-header mt-10 text-center mb-3">
        <h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
        <p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements using this web application.</p>
        <p>
			<u> Step {{ wizard.steps.step1 }} of  {{ wizard.steps.count }} </u>
		</p>
    </div> -->

    <div class="post-content">
        
        <form action="" class="site-form" method="post">
            {% csrf_token %}
            <div class="mb-5 site-form-header bg-indigo-300 rounded px-2">
                <h2 class="text-center">Create a Digital Level</h2>
            </div>
            <table>
                {% for field in form %}
                <tr>
                    <td width="25%"><strong>{{ field.label_tag }}</strong></td>
                    <td width="70%"> {{ field }} 
                        <!-- Errors -->
                        {% for error in field.errors %}
                            <p class="error error-danger">{{ error }}</p>
                        {% endfor %}
                        <!-- Help text -->
                        {% if not field.field.widget.attrs.placeholder and field.help_text %}
                            <p class="helptext">{{ field.help_text }}</p>
                        {% endif %}
                    </td>
                    <td width="5%">
                            {% if 'model' in field.name %}
                                <button class="ml-3 px-2 py-1 bg-green-400 border-transparent hover:border-gray-900 rounded text-lg text-white cursor-pointer" onclick="return showAddPopup(this);">&#43;</button>
                            {% elif 'coefficient' in field.name %}
                                <span>ppm</span>
                            {% elif 'length' in field.name %}
                                <span>m</span>
                            {% endif %}
                            
                    </td>
                </tr>
                {% endfor %}               
            </table>

            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <div class="button-container">
                <button class="submit-button bg-green-400 hover:bg-green-300 text-base" type="submit" >Submit</button>
            </div>

        </form>
    </div>
</article>

<script>
        function showAddPopup(triggeringLink) {
        // var name = triggeringLink.id.replace(/^add_/, '');
        // console.log(name)
        // href = triggeringLink.href;
        // console.log(href)
        var win = window.open("{% url 'instruments:inst_model_createby_inst_type' 'level' %}", "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=850,width=500,height=400");
        // var win = window.open(href, name, 'height=500,width=800, resizable=yes,scrollbars=yes');
        win.focus();
        return false;
    }

    modelOptions = document.querySelector("#id_level_model")
    function closePopup(win, newID, newRepr) {
        // $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
        // console.log(id, newID, newRepr)
        window.sessionStorage.setItem('new_model',  newID);
        win.close();
    }
    

    let newModelValue = sessionStorage.getItem('new_model');
    if (newModelValue) {
        for(var i = 0;i < modelOptions.options.length;i++){
                if(modelOptions.options[i].value == newModelValue ){
                    modelOptions.options[i].selected = true;
                }
            }
        
        window.sessionStorage.clear()
    }
</script>

{% endblock %}

instruments/templates/instruments/inst_level_create_popup_form.html
{% extends 'base_popup.html' %}
{% load i18n %}
{% load static %}

{% block content %} 

<article class="post">
    <!-- <div class="post-header mt-10 text-center mb-3">
        <h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
        <p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements using this web application.</p>
        <p>
			<u> Step {{ wizard.steps.step1 }} of  {{ wizard.steps.count }} </u>
		</p>
    </div> -->

    <div class="post-content">
        
        <form action="" class="site-form" method="post">
            {% csrf_token %}
            <div class="mb-5 site-form-header bg-indigo-300 rounded px-2">
                <h2 class="text-center">Create a Digital Level</h2>
            </div>
            <table>
                {% for field in form %}
                <tr>
                    <td width="25%"><strong>{{ field.label_tag }}</strong></td>
                    <td width="70%"> {{ field }} 
                        <!-- Errors -->
                        {% for error in field.errors %}
                            <p class="error error-danger">{{ error }}</p>
                        {% endfor %}
                        <!-- Help text -->
                        {% if not field.field.widget.attrs.placeholder and field.help_text %}
                            <p class="helptext">{{ field.help_text }}</p>
                        {% endif %}
                    </td>
                    <td width="5%">
                            {% if 'model' in field.name %}
                                <a href="/instruments/inst_model_createby_inst_type/level/" target="_blank" class="ml-3 px-2 py-1 bg-green-400 border-transparent hover:border-gray-900 rounded text-lg text-white cursor-pointer" onclick="return showAddPopup(this);" id="add_level">&#43;</a>
                                <!-- <button class="ml-3 px-2 py-1 bg-green-400 border-transparent hover:border-gray-900 rounded text-lg text-white cursor-pointer" onclick="return showAddPopup(this);">&#43;</button> -->
                            {% elif 'coefficient' in field.name %}
                                <span>ppm</span>
                            {% elif 'length' in field.name %}
                                <span>m</span>
                            {% endif %}
                            
                    </td>
                </tr>
                {% endfor %}               
            </table>

            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <div class="button-container">
                <button class="submit-button bg-green-400 hover:bg-green-300 text-base" type="submit" >Submit</button>
            </div>

        </form>
    </div>
</article>

<script>
        function showAddPopup(triggeringLink) {
        var name = triggeringLink.id.replace(/^add_/, '');
        href = triggeringLink.href;
        // var win = window.open("{% url 'instruments:inst_model_createby_inst_type' 'level' %}", "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=850,width=500,height=400");
        var win = window.open(href, name, "toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=850,width=500,height=400");
        win.focus();
        return false;
    }

    modelOptions = document.querySelector("#id_level_model")
    function closePopup(win, newID, newRepr) {
        // $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
        // console.log(id, newID, newRepr)
        window.sessionStorage.setItem('new_model',  newID);
        win.close();
    }
    

    let newModelValue = sessionStorage.getItem('new_model');
    if (newModelValue) {
        for(var i = 0;i < modelOptions.options.length;i++){
                if(modelOptions.options[i].value == newModelValue ){
                    modelOptions.options[i].selected = true;
                }
            }
        
        window.sessionStorage.clear()
    }
    //  Refresh Parent Function
    function refreshParent() 
        {
            window.opener.location.reload(true);
        }
</script>

<body onunload="javascript:refreshParent()">

{% endblock %}

instruments/templates/instruments/inst_staff_create_form.html
{% extends 'base_generic.html' %}
{% load i18n %}
{% load static %}

{% block content %} 

<article class="post">
    <!-- <div class="post-header mt-10 text-center mb-3">
        <h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
        <p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements using this web application.</p>
        <p>
			<u> Step {{ wizard.steps.step1 }} of  {{ wizard.steps.count }} </u>
		</p>
    </div> -->

    <div class="post-content">
        
        <form action="" class="site-form" method="post">
            {% csrf_token %}
            <div class="mb-5 site-form-header bg-indigo-300 rounded px-2">
                <h2 class="text-center">Create a Barcoded Levelling Staff</h2>
            </div>
            <div class="mb-3 px-2 site-form-header">
                <p class="text-center text-lg"><u>Step {{ wizard.steps.step1 }} of  {{ wizard.steps.count }}</u></p>
            </div>
            <table>
                {{ wizard.management_form }}
                {% if wizard.form.forms %}
                    {{ wizard.form.management_form }}
                    {% for form in wizard.form.forms %}
                        {{ form }}
                    {% endfor %}
                {% else %}
                    {% for field in wizard.form %}
                    <tr>
                        <td width="25%"><strong>{{ field.label_tag }}</strong></td>
                        <td width="70%"> {{ field }} 
                            <!-- Errors -->
                            {% for error in field.errors %}
                                <p class="error error-danger">{{ error }}</p>
                            {% endfor %}
                            <!-- Help text -->
                            {% if not field.field.widget.attrs.placeholder and field.help_text %}
                                <p class="helptext">{{ field.help_text }}</p>
                            {% endif %}
                        </td>
                        <td width="5%">
                                {% if 'model' in field.name %}
                                   <a href="/instruments/inst_model_createby_inst_type/staff/" target="_blank" class="ml-3 px-2 py-1 bg-green-400 border-transparent hover:border-gray-900 rounded text-lg text-white cursor-pointer" onclick="return showAddPopup(this);" id="add_staff">&#43;</a>
                                {% elif 'coefficient' in field.name %}
                                    <span>ppm</span>
                                {% elif 'length' in field.name %}
                                    <span>m</span>
                                {% endif %}
                                
                        </td>
                    </tr>
                    {% endfor %}               
                {% endif %}
            </table>

            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <!-- <div class="button-container">
                <button class="submit-button bg-green-500 hover:bg-green-400" type="submit" >Submit</button>
            </div> -->
            <div class="wizard-button-container">
				{% if wizard.steps.prev %}
					<button class="next-button bg-indigo-400 hover:bg-indigo-300 text-base" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}" formnovalidate> {% trans "<span>&#171;</span> Previous" %}</button>
                    <!-- <button class="next-button bg-green-500 hover:bg-green-300" name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}" formnovalidate>{% trans "First" %}</button> -->
                {% endif %}

				{% if wizard.steps.next %}
					<button class="next-button bg-green-400 hover:bg-green-300 text-base" type="submit">Next <span>&#187;</span></button>
					<a href="{% url 'instruments:home' %}" class="cancelbtn bg-red-500 hover:bg-red-300 text-center">Cancel</a>
				{% else %}
					<button class="next-button bg-green-400 hover:bg-green-300 text-base" type="submit">Submit <span>&#187;</span></button>
					<a href="{% url 'instruments:home' %}" class="cancelbtn bg-red-500 hover:bg-red-300 text-center">Cancel</a>
				{% endif %}
			</div>

        </form>
    </div>
</article>

<script>
    function showAddPopup(triggeringLink) {
        var name = triggeringLink.id.replace(/^add_/, '');
        href = triggeringLink.href;
        // var win = window.open("{% url 'instruments:inst_model_createby_inst_type' 'staff' %}", "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=850,width=500,height=400");
        var win = window.open(href, name, "toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=850,width=500,height=400");
        win.focus();
        return false;
    }

    modelOptions = document.querySelector("#id_inst_staff_form-staff_model")
    function closePopup(win, newID, newRepr) {
        window.sessionStorage.setItem('new_model',  newID);
        win.close();
    }
    

    let newModelValue = sessionStorage.getItem('new_model');
    if (newModelValue) {
        for(var i = 0;i < modelOptions.options.length;i++){
                if(modelOptions.options[i].value == newModelValue ){
                    modelOptions.options[i].selected = true;
                }
            }
        
        window.sessionStorage.clear()
    }
    
    function refreshParent() 
        {
            window.opener.location.reload(true);
        }
</script>

<body onunload="javascript:refreshParent()">


{% endblock %}

instruments/templates/instruments/instruments_home.html
{% extends 'base_generic.html' %}
{% load static %}


{% block content %}

<article class="post mt-10">
    {% if messages %}
		<ul class="alert messages">
		    {% for message in messages %}
		    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		    {% endfor %}
		</ul>
		<br>
	{% endif %}	
	
	<header class="post-header">
		<h1 class="post-title text-center">Welcome to Landgate's Survey Instrument Calibration website.</h1>
		<br>
        <p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements using this web application.</p>
		<p>Add/view your digital levels and bar-coded staves here.</p>
	</header>

	<div class="post-content mt-10">
		<div class="grid-2l items-center">
			<div class="px-2 flex flex flex-col space-around items-center">
				<h3>Create a New Instrument Model</h3>
				<a href="{% url 'instruments:inst_model_create' %}?reset">
					<button class="px-3 py-1 border border-transparent text-base leading-4 rounded text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">
						Create
					</button>
				</a>
			</div>
			<div class="px-2">
				<h3 class="text-center">Avaliable Instrument Models</h3>
				<table style="table-layout: fixed; width: 95%"> 
						<tr>
							<th>Instrument Type</th>
							<th>Model Name</th>
							<th>Make</th>
						</tr>			
						{% for model in model_list %}
						<tr>
							<td>{{ model.get_inst_type_display }} </td>
							<td>{{ model.model }} </td>
							<td>{{ model.make }} </td>
						</tr>
						{% endfor %}
					</table>
			</div>
			
			
		</div>  
		<br><br>
		<hr>
		<div class="grid-2l items-center">
			<div class="px-2 flex flex flex-col space-around items-center border-gray-300">
				<h3 class="pxr-5">Create a New Barcoded Staff</h3>
				<a href="/instruments/inst_staff_create/?reset">
					<button class="px-3 py-1 border border-transparent text-base leading-4 rounded text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">
						Register
					</button>
				</a>
			</div>
			<div>
				<h3 class="text-center">Available Bar-Code staves</h3>
				<table style="table-layout: fixed; width: 95%"> 
						<tr>
							<th>Staff Number</th>
							<th>Staff Model</th>
							<th>Staff Type</th>
							<th>Staff Length</th>
							<th>Coefficient (in ppm)</th>
						</tr>			
						{% for staff in staff_list %}
						<tr>
							<td>{{ staff.staff_number }} </td>
							<td>{{ staff.staff_model }} </td>
							<td>{{ staff.staff_type }} </td>
							<td>{{ staff.staff_length }} </td>
							<td>{{ staff.thermal_coefficient }} </td>
	
						</tr>
						
						{% endfor %}
					</table>
			</div>
		</div>
		<br><br>
		<hr>
		<div class="grid-2l items-center">
			<div class="px-2 flex flex flex-col space-around items-center border-gray-300">
				<h3 class="pxr-5">Create a New Digital Level</h3>
				<a href="{% url 'instruments:inst_level_create' %}?reset">
					<button class="px-3 py-1 border border-transparent text-base leading-4 rounded text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">
						Register
					</button>
				</a>
			</div>
			<div>
				<h3 class="text-center">Available Digital levels</h3>
				<table style="table-layout: fixed; width: 95%"> 
						<tr>
							<th>Level Number</th>
							<th>Level Model</th>
							<th>Level Owner</th>
						</tr>			
						{% for level in level_list %}
						<tr>
							<td>{{ level.level_number }} </td>
							<td>{{ level.level_model }} </td>
							<td>{{ level.level_owner }} </td>
							
						</tr>
						
						{% endfor %}
					</table>
			</div>
		</div>  
	</div>
</article>
{% endblock content %}
