accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', RedirectView.as_view(url='/', permanent=False), name='home'),
    path('user_account/', views.user_account, name ='user_account'),
    path('signup/', views.user_signup, name='signup'),
    path('sent/', views.activation_sent, name = 'activation_sent'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate_account, name='activate_account'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
    	template_name="registration/password_reset_form.html",
    	email_template_name = "registration/password_reset_email.html",
        success_url = reverse_lazy("accounts:password_reset_done")), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view( template_name="registration/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view( template_name="registration/password_reset_confirm.html",
        success_url = reverse_lazy("accounts:password_reset_complete")), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view( template_name="registration/password_reset_complete.html"), name='password_reset_complete'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('user_profile/<email>/', views.user_update_for_admin, name='user_update_for_admin'),
    path('user_accounts/accounts/<email>/delete', views.user_delete_for_admin, name='user_delete_for_admin'),
    path('company/<id>/update', views.company_update, name = 'company_update'),
    path('company/<id>/delete', views.company_delete, name = 'company_delete'),
    path('company/create', views.company_create, name = 'company_create'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Company(models.Model):
    company_name = models.CharField(max_length=200, unique=True)
    company_abbrev = models.CharField(max_length=20)

    def __str__(self):
        return self.company_name
        
####### CUSTOM MANAGER TO MAKE EMAIL AS UNIQUE ID INSTEAD OF USERNAME ######
class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email).lower()
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        # user.is_admin = False;
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

class LowerCaseEmailField(models.EmailField):
    """
    Override email field to convert to lowercase
    """
    def to_lower_case(self, value):
        value = super(LowerCaseEmailField, self).to_lower_case(value)
        if isinstance(value, str):
            return value.lower()
        return value

class CustomUser(AbstractUser):
    company = models.ForeignKey(
                                Company,
                                on_delete = models.SET_NULL,
                                blank = True,
                                null = True,
    )

    username = None
    email = LowerCaseEmailField(_('email address'), 
                                max_length = 150,
                                unique=True,
                                error_messages = {
                                    'unique': _("The user with that email address already exists.")
                                })
    # email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

class Calibration_Report_Notes(models.Model):
    company = models.ForeignKey(Company, on_delete = models.CASCADE, null = False)
    report_types = (
                 ('B','Baseline Calibration'),
                 ('R','Range Calibration'),
                 ('E', 'EDMI Calibration'),
                 ('S', 'Staff Calibration')
                 )
    report_type = models.CharField(max_length=1,
                 choices=report_types,
                 help_text="Report type that the notes will be added to",
                 unique=False,
                 )
    note_types = (
                 ('M','Manditory'),
                 ('C','Company Specific'),
                 )
    note_type = models.CharField(max_length=1,
                 choices=note_types,
                 help_text="Will this note appear accross all company reports",
                 unique=False,
                 )    
    note = models.TextField(null = False, blank = False,
                 verbose_name= 'Report Note',
                 help_text="Notes to be detailed at the end of each report")

    class Meta:
        ordering = ['company','report_type','note_type']


    def __str__(self):
        return f'{self.pk}. {self.company} - {self.get_report_type_display()} ({self.get_note_type_display()})'
    
    
    
    
    
    
    
    
    
    
    
    
    

accounts/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import ReadOnlyPasswordHashField, UserCreationForm, UserChangeForm


from .models import CustomUser, Company

class SignupForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    company = forms.ModelChoiceField(empty_label='Choose your firm/company',
                                    queryset=Company.objects.all(),
                                    widget=forms.Select())
    
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'company', 'password1', 'password2')
    
    def clean_email(self):
        return self.cleaned_data.get('email').lower()

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        password_validation.validate_password(self.cleaned_data.get('password1'), None)
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class CustomUserChangeForm(ModelForm):
    # password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ['email', 'company']

    # def clean_password(self):
    #     return self.initial["password"]

class LoginForm(forms.Form): 
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'class': 'form-control','type':'text','name': 'email','placeholder':'Email address'}), 
        label='Email Address')
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class':'form-control','type':'password', 'name': 'password','placeholder':'Password'}),
        label='Password')

    class Meta:
        fields = ['email', 'password']
        # widgets = {
        #     'password': forms.PasswordInput(attrs={'placeholder':'********','autocomplete': 'off','data-toggle': 'password'}), 
        # }
    
    def clean_email(self):
        return self.cleaned_data.get('email').lower()

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['company_name','company_abbrev']
        
        widgets = {
            'company_name' : forms.TextInput(attrs={'placeholder':'Enter a company, e.g., Landgate'}),
            'company_abbrev' : forms.TextInput(attrs={'placeholder':'Give an abbreviation, e.g., LG'}),
        }

    def clean_company_abbrev(self):
        company_abbrev = self.cleaned_data['company_abbrev'].upper()
        return company_abbrev

accounts/templates/accounts/login.html
{% extends 'base_generic.html' %}
{% load static %}

{% block content %}

<article class="post">
    <header class="post-header mt-12 text-center mb-3">
        <h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
        <p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements using this web application.</p>
    </header>

    <div class="post-content">

        <form action="{% url 'accounts:login' %}" class="site-form" method="post">
            <div class="mb-5 site-form-header bg-indigo-300 rounded px-2">
                <h2 class="text-center">Login Form </h2>
            </div>

            <div class="form-container">
                {% csrf_token %}
                <table>
                    {% for field in login_form %}
                        <tr>
                            <td width="20%">{{ field.label_tag }}</td>
                            <td width="50"> 
                                {{ field }}
                                 <!-- Errors -->
                                {% for error in field.errors %}
                                    <p class="error error-danger">{{ error }}</p>
                                {% endfor %}
                                <!-- Help text -->
                                {% if not field.field.widget.attrs.placeholder and field.help_text %}
                                    <p class="helptext">{{ field.help_text }}</p>
                                {% endif %}
                            </td>
                            <td width="20%"></td>
                        </tr>
                    {% endfor %}
                </table>
                
                <!-- {{ login_form }} -->

                <!--  redirect -->
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
              
            </div>    
            
            <div class="button-container">
                <button class="submit-button bg-green-400 hover:bg-green-300 text-base" type="submit" >Log in</button>
                
                <div class="registerbtn-container">
                    <span> Forgot <a href="{% url 'accounts:password_reset' %}" class="text-blue-500">Password</a>?</span>
                    <a href="{% url 'accounts:signup' %}" class="registerbtn bg-blue-400 hover:bg-blue-200">Register</a>
                </div>
                <a href="{% url 'home' %}" class="cancelbtn bg-red-500 hover:bg-red-300 text-center">Cancel</a>
            </div>
            
        </form>
    </div>
</article>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_generic.html' %}
{% load static %}

{% block content %}
	<article class="post">
		<header class="post-header mt-12 text-center mb-3">
            <h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
            <p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements using this web application.</p>
        </header>

        {% if messages %}
        <ul class="message-list">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        <!-- <br> -->
        {% endif %}

        <div class="post-content">
            
            <form class="site-form" action="{% url 'accounts:signup' %}" method="post">     
                <div class="mb-5 site-form-header bg-indigo-300 rounded px-2">
                    <h2 class="text-center">Signup Form </h2>
                </div>          
                <div class="form-container">
                    {% csrf_token %}
                    <table>
                        <colgroup>
                            <col span="1" width="30%">
                            <col span="2" width="70%">
                        </colgroup>
                        {% for field in form %}
                            <tr>
                                <td>{{ field.label_tag }}</td>
                                <td> 
                                    {{ field }}
                                     <!-- Errors -->
                                    {% for error in field.errors %}
                                        <p class="error error-danger">{{ error }}</p>
                                    {% endfor %}
                                    <!-- Help text -->
                                    {% if not field.field.widget.attrs.placeholder and field.help_text %}
                                        <p class="helptext">{{ field.help_text }}</p>
                                    {% endif %}
                                </td>
                            </tr>
                            {% if field.name == "company" %}
                                <tr id="id_company_name">
                                    <td><label for="company_name" class="text-sm text-blue-500">Company Name:</label> </td>
                                    <td> <input type="text" name="company_name" placeholder="Enter Company name" class="text-blue-500"> </td>
                                </tr>
                                <tr id="id_company_abbr">
                                    <td><label for="company_abbrev" class="text-sm text-blue-500">Abbreviation:</label></td> 
                                    <td><input type="text" name="company_abbrev" placeholder="Enter short name" class="text-blue-500"></td> 
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                    
                    <label for="remember">
                        <input type="checkbox" name="remember" id="remember"> 
                        By signing in, I agree to all the terms & conditions contained in this <a href="{% url 'terms' %}">user agreement</a>. 
                    </label>
                </div>

                <div class="form-container reset-password-container">
                    <button type="submit" name="login" class="submit-button text-base">Register</button>
                </div>
            </form>
        </div>

        <script type="text/javascript">
            // const log = console.log;
            const defaultCompanyText = document.querySelector('#id_company option[value=""')
            if (defaultCompanyText) {
                defaultCompanyText.setAttribute('class', 'default');
                defaultCompanyText.setAttribute('value', '');
            }

            const companySelect = document.querySelector(`[id="id_company"]`);
            const newCompanyName = document.getElementById("id_company_name")
            const newCompanyAbbr = document.getElementById("id_company_abbr")
            
            // Display None
            newCompanyName.style.display = "none"
            newCompanyAbbr.style.display = "none"

            companySelect.addEventListener(`change`, (e) => {
              // log(`e.target`, e.target);
              const select = e.target;
              const value = select.value;
              const desc = select.options[select.selectedIndex].text;
              // log(`value desc`, value, desc);
              if (desc=="Others") {
                //   document.getElementById("companyDiv").style.display = "table-row";
                newCompanyName.style.display = "table-row";
                newCompanyAbbr.style.display = "table-row";
              } else {
                //   document.getElementById("companyDiv").style.display = "none";
                newCompanyName.style.display = "none";
                newCompanyAbbr.style.display = "none";
              }
            });
        </script>
{% endblock %}

accounts/templates/accounts/user_accounts.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
	<article class="post">
		<div class="post-header mt-12 text-center mb-3">
			<h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
			<p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements online.</p>
		</div>

		{% if messages %}
        <ul class="message-list">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        <!-- <br> -->
        {% endif %}
		
		<div class="post-content">
			<div class="tab-wrap">
				<input id="tab1" type="radio" name="tabs" checked="checked">
				<label for="tab1">My Profile</label>
				<input id="tab2" type="radio" name="tabs">
				<label for="tab2">List of Users</label>
				{% if request.user.is_staff %}
					<input id="tab3" type="radio" name="tabs">
					<label for="tab3">Companies</label>
				{% endif %}
				<input id="tab4" type="radio" name="tabs">
				<label for="tab4">Calibration Records</label>
				<!-- tab panel -->
				<section id="content1">
					<h3>My Info</h3>
					<p>You can update your information by clicking the update button.</p>
					<div class="form-container">
						<table>
							<tr>
								<td><strong>My email</strong></td>
								<td>{{ this_user.email }}</td>
							</tr>
							<tr>
								<td><strong>My name</strong></td>
								<td>{{ this_user.first_name }} {{ this_user.last_name }}</td>
							</tr>
							<tr>
								<td><strong>My company</strong></td>
								<td>{{ this_user.company }}</td>
							</tr>
							<tr>
								<td><strong>My last login</strong></td>
								<td>{{ this_user.last_login }}</td>
							</tr>
						</table>
						<br>
						<div class="form-container reset-password-container">
							<a class="ml-5 px-3 py-2 border border-transparent text-sm leading-3 font-medium rounded text-white bg-gray-600 hover:bg-gray-300 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out" href="{% url 'accounts:user_profile' %}">Update my info</a>
						</div>
						<br>
					</div>
					
				</section>
				<section id="content2">
					<h3>List of Users</h3>
				  	{% if request.user.is_staff %}
					  <p>You can update or delete the users.</p>
					{% else %}
						<p>All the users in <strong>{{ request.user.company }}</strong>.</p>
					{% endif %}

					{% if user_page_obj %}
						<table>
							<tr>
								<th>Sl No.</th>
								<th>Email address</th>
								<th>Name</th>
								{% if request.user.is_staff %}
									<th>Company</th>
								{% endif %}
								<!-- <th>Date joined</th> -->
								<th>Last active</th>
								<th>Update/Delete</th>
							</tr>
							{% for luser in user_page_obj %}
								<tr> 
									<td>{{ forloop.counter|add:-1|add:user_page_obj.start_index }}</td>
									<td>{{ luser.email }}</td>
									<td>
										{% if luser.first_name %} 
										{{ luser.last_name|default_if_none:"" }}, {{ luser.first_name}}
										{% else %}
										{{ "" }}
										{% endif %}
									</td>
									{% if request.user.is_staff %}
										<td>{{ luser.company.company_name }} </td>
									{% endif %}
									<!-- <td>{{ luser.date_joined|date }} </td> -->
									<td>{{ luser.last_login }} </td>
									<td class="tab-button">
										  <a class="svg-icon edit" href="{% url 'accounts:user_update_for_admin' luser.email %}" >
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000" class="bi bi-pencil-fill" viewBox="0 0 16 16">
												<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
											</svg>
										</a>
										<a class="svg-icon trashcan" href="{% url 'accounts:user_delete_for_admin' luser.email %}" >
											<svg width="16" height="16" viewBox="0 0 16 16" fill="red" class="bi bi-trash" onclick="return confirmation()">
												<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
												<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
										  </svg> </a>
									</td>
								</tr>
								
							{% endfor %}
						</table>
					{% else %}
						<p> There are currently no users in our system </p>
					{% endif %}
					{% if user_page_obj.has_other_pages  %}
						<div class="pagination">
							<span class="step-links">
								{% if user_page_obj.has_previous %}
									<a href="?page=1">« first</a>
									<a href="?page={{ page_obj.previous_page_number }}">previous</a>
								{% endif %}
						
								<span class="current">
									Page {{ user_page_obj.number }} of {{ user_page_obj.paginator.num_pages }}.
								</span>
						
								{% if user_page_obj.has_next %}
									<a href="?page={{ user_page_obj.next_page_number }}">next</a>
									<a href="?page={{ user_page_obj.paginator.num_pages }}">last »</a>
								{% endif %}
							</span>
						</div>
					{% endif %}
				</section>
				{% if request.user.is_staff %}
				<section id="content3">
					<h3>List of Companies</h3>
				  	<p>Scroll down to click the pages. Click <a class="a_link" href="{% url 'accounts:company_create' %}" target="__blank">here</a> to create a new record.</p>
				  	{% if company_page_obj %}
				  	<table>
					  	<tr>
							<th>Sl No.</th>
						  	<th>Company Name</th>
						  	<th>Company Abbreviation</th>
						  	<th>Update or Delete</th>
					  	</tr>
					  	{% for c in company_page_obj %}
						  	<tr> 
								<td>{{ forloop.counter|add:-1|add:company_page_obj.start_index }}</td>
								<td>{{ c.company_name }}</td>
								<td>{{ c.company_abbrev }}</td>
								<td class="tab-button">
									<a class="svg-icon edit" href="{% url 'accounts:company_update' c.id %}" >
										<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000" class="bi bi-pencil-fill" viewBox="0 0 16 16">
											<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
										</svg>
									</a>
									<a class="svg-icon trashcan" href="{% url 'accounts:company_delete' c.id %}">
										<svg width="16" height="16" viewBox="0 0 16 16" fill="red" class="bi bi-trash" onclick="return confirmation()">
										<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
											<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
										</svg>
									</a>
								</td>
						  	</tr>
					  	{% endfor %}
				  	</table>
			 	 {% else %}
				  	<p> There are currently no Companies listed in our system </p>
			  	{% endif %}
				{% if company_page_obj.has_other_pages  %}
				  	<div class="pagination">
						<span class="step-links">
							{% if company_page_obj.has_previous %}
								<a class="a_link" href="?page=1"> First</a>
								<a class="a_link" href="?page={{ page_obj.previous_page_number }}"><span>&#171;</span>Previous</a>
							{% endif %}
					
							<span class="current">
								Page {{ company_page_obj.number }} of {{ company_page_obj.paginator.num_pages }}
							</span>
					
							{% if company_page_obj.has_next %}
								<a class="a_link" href="?page={{ company_page_obj.next_page_number }}">Next<span>&#187;</span></a>
								<a class="a_link" href="?page={{ company_page_obj.paginator.num_pages }}">Last</a>
							{% endif %}
						</span>
					</div>
				{% endif %}
			</section>
			{% endif %}
			<section id="content4">
				<h3>My most recent calibration records</h3>
				<p>Here is a list of my calibrated instruments.</p>
				<!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, exercitationem dolore explicabo alias odio quos enim, ullam reiciendis cum autem atque, optio natus quae nisi dolorum? Voluptates sunt iusto harum?</p> -->
				{% if staff_list %}
				<h2>Levelling Staves</h2>
				<table>
					<tr>
						<th>Sl No.</th>
						<th>Job Number</th>
						<th>Instrument No</th>
						<th>Model</th>
						<th>Type</th>
						<th>Scale Factor</th>
						<th>Field Book</th>
						<th>Calibrated on</th>
						<th>Certificate</th>
					</tr>
					{% for element in staff_list %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{ element.job_number }}</td>
						<td> <a class="a_link" href="{{ element.inst_staff.get_absolute_url }}">{{ element.inst_staff.staff_number }}</a> </td>
						<td>{{ element.inst_staff.staff_model.model }} ({{ element.inst_staff.staff_model.make }})</td>
						<td>{{ element.inst_staff.staff_type|title }}</td>
						<td>{{ element.scale_factor|stringformat:"1.6f" }}</td>
						<td>
							{% if element.field_url %}
								<a href="{{ element.field_url|default_if_none:'#' }}" target="__blank">Click link</a></td>
							{% else %}
								<a href="#">None</a>
							{% endif %}
						<td>{{ element.calibration_date }}</td>
						
						<td>
							{% if element.report_url %}
								<a href="{{ element.report_url|default_if_none:'#' }}" target="__blank">Click here</a>
							{% elif element.field_book %}
								<a href="{% url 'staffcalibration:print-report' element.job_number %}" target="__blank">Click here</a>
							{% endif %}
						</td>
					</tr>
					
					{% endfor %}
				</table>
				{% endif %}
				<br>

				{% if edm_list %}
					<h2>Levelling Staves</h2>
				{% endif %}
		
			</section>
			</div>
		</div>

		

	</article>
	
	<script type="text/javascript">
		function confirmation() {
	      return confirm('Are you sure you want to delete this record? You will not be able to retreive the record later.');
	    }
	</script>

	<script>
		var data_tabs = document.querySelectorAll('input[name="tabs"]');
		for (var i = 0; i < data_tabs.length; i++) {
			// console.log(data_tabs[i].checked);
			data_tabs[i].addEventListener('click', function() {
				this.setAttribute('checked', 'checked');
				this.checked = true;
				window.localStorage.setItem("activeTab", this.id)	

			})
		}

		var activeTab = window.localStorage.getItem('activeTab');
		if (activeTab) {
			for (var i = 0; i < data_tabs.length; i++) {
				if (data_tabs[i].id == activeTab) {
					data_tabs[i].checked = true;
				}
			}
		}

		let file;
		function checkFile() {
		file = document.querySelector('input[type=file]').files[0];
		if (file.type != '.pdf' | file.type != '.jpg') {
			file = null;
		document.getElementById('id_document').remove();
		}
		}
	</script>

{% endblock %}