baseline_calibration/urls.py
from django.urls import path
from . import views
#from .views import CreateInstrumentWizard      

app_name = 'baseline_calibration'

urlpatterns = [
    path('', views.calibration_home, name = 'calibration_home'),
    path('calibrate1/<slug:id>', views.calibrate1, name = 'calibrate1'),
    path('calibrate2/<int:id>', views.calibrate2, name = 'calibrate2'),
    path('pillar_survey_del/<int:id>', views.pillar_survey_del, name = 'pillar_survey_del'),
    path('uc_budgets/', views.uc_budgets, name = 'uc_budgets'),
    path('uc_budget/create/', views.uc_budget_create, name = 'uc_budget_create'),
    path('uc_budget/<int:id>/edit/', views.uc_budget_edit, name = 'uc_budget_edit'),
    path('uc_budget/<int:id>/delete/', views.uc_budget_delete, name = 'uc_budget_delete'),
    
]

baseline_calibration/templates/baseline_calibration/Home.html
{% extends 'base_generic.html' %}
{% load static %}


{% block content %}

<article class="post">
    <div class="mt-10">
        {% if not user.is_authenticated %}
            <p class="text-lg">Please 
                <a href="{% url 'accounts:login' %}" class="hover:a">
                    login
                </a> or 
                <a href="{% url 'accounts:signup' %}" class="hover:a">
                    signup
                </a> to manage and calibrate your surveying instruments.</p>
        {% endif %}
    </div>
    {% if messages %}
        <ul class="alert messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        <br>
    {% endif %}	
    <div class="container_IB">
        <div class="post-content">
						<h2 class="text-center">List of Company Pillar Calibration Surveys</h2>
        				<div class="mt-2 flex justify-center">
                		<a href="{% url 'baseline_calibration:calibrate1' id=None %}">
                    <button class="px-3 py-2 border border-transparent text-lg leading-4 rounded text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">
                    &#x2B Add new calibration
                    </button>
                  	</a>  
                </div>
        <br>
        <hr>
				{% if pillar_surveys %}
					<table style="font-size:10pt;width: 100%"> 
          		<col span="1" style="width: 15%">
              <col span="1" style="width: 15%">
              <col span="1" style="width: 15%">
              <col span="1" style="width: 15%">
              <col span="1" style="width: 10%">
              <col span="1" style="width: 20%">
              <col span="1" style="width: 10%">
							<tr>
									<th>Baseline</th>
									<th>Job Number</th>
									<th>Survey Date</th>
									<th>Company</th>
									<th>Observed By</th>
									<th>Certified Distances Modified</th>
									<th>&nbsp Action</th>
							</tr>			
						{% for pillar_survey in pillar_surveys %}
							<tr>
									<td>{{ pillar_survey.baseline }} </td>
									<td>{{ pillar_survey.job_number }} </td>
									<td>{{ pillar_survey.survey_date }} </td>
									<td>{{ pillar_survey.accreditation.accredited_company }}</td>
									<td>{{ pillar_survey.observer }} </td>
	        						<td>{{ pillar_survey.modified_on }}</td>
									<td><a href= "{% url 'baseline_calibration:calibrate1' id=pillar_survey.pk %}" style="color:green;cursor:pointer;cursor:hand">Edit</a> | 
									<a href= "{% url 'baseline_calibration:pillar_survey_del' id=pillar_survey.pk %}" style="color:red;cursor:pointer;cursor:hand">Delete</a></td>
							</tr>
						{% endfor %}
						</tr>
					</table>
					
				{% else %}
        <p> There are currently no baselines with calibration pillar surveys.</p>
				{% endif %}

        </div>
    </div>
</article>

<script>

</script>

 {% endblock content %}

baseline_calibration/templates/baseline_calibration/Uncertainty_budgets_list.html
{% extends 'base_generic.html' %}
{% load static %}

{% block content %}
<article class="post">
		<div class="flexbox-container_IB">
				<div class="flexbox-item_800_IB">
				    <div class="mt-10">
				    {% if not user.is_authenticated %}
				    <p class="text-lg">Please 
				    		<a href="{% url 'accounts:login' %}" class="hover:a">
				        login
				        </a> or 
				        <a href="{% url 'accounts:signup' %}" class="hover:a">
				        signup
				        </a> to manage and calibrate your surveying instruments.
				    </p>
				    {% endif %}
				    <h2 class="text-center">List of Uncertainty Budgets</h2>
				    <div style="text-align:center;font-size:10pt">
				    		<a href="{% url 'baseline_calibration:uc_budget_create' %}?next={{request.path}%}" >
                <button class="px-3 py-2 border border-transparent text-lg leading-4 rounded text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">
                &#x2B Add new uncertainty budget</button>
            </a> 
            </div>
				    <br><i style="ifont-size:10pt">Predefined uncertainty budgets for selection during Baseline or EDMI Calibration procedure</i></br>
				    <hr>
				    {% if messages %}
				    <ul class="alert messages">
				    		{% for message in messages %}
				        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				        {% endfor %}
				    </ul>
				    {% endif %}	
				    <div class="flexbox-item_800_IB">
				        <div class="post-content">
				            <div id="uncertainty-budget-list">
										{% if uc_budget_list %}
												<table style="font-size:10pt;width:100%"> 
							              <col span="1" width="28%">
							              <col span="1" width="28%">
							              <col span="1" width="32%">
							              <col span="1" width="12%">
														<tr>
																<th>Name</th>
																<th>Created by</th>
																<th>Std Dev used when statistically zero</th>
																<th>&nbsp&nbsp Action</th>
														</tr>			
														{% for budget in uc_budget_list %}
														<tr>
																<td>{{ budget.name }}</td>
																<td>{{ budget.company }}</td>
																<td>{{ budget.std_dev_of_zero_adjustment }}</td>
																{% if budget.name == "Default" and budget.company.company_name == "Landgate" %}
									    					<td></td>
																{% else %}
									    					<td>
									    							<a href="{% url 'baseline_calibration:uc_budget_edit' id=budget.pk %}" style="color:green;cursor:pointer;cursor:hand">Edit</a> |
									    							<a href="{% url 'baseline_calibration:uc_budget_delete' id=budget.pk %}" style="color:red;cursor:pointer;cursor:hand;">Delete</a>
									    					</td>
																{% endif %}
														</tr>
														{% endfor %}
											  </table>									
										{% else %}
				            <p>There are currently no uncertainy budgets!</p>
										{% endif %}
										</div>
				        </div>
				    </div>
			  </div>    
	  </div>
</article>
<script>
</script>
{% endblock content %}

baseline_calibration/templates/baseline_calibration/calibrate.html
{% extends 'base_generic.html' %}
{% load static %}


{% block content %} 

<article class="post">
    <div class="post-header mt-12 text-center mb-3">
        {% for pg, Header in Headers.items %}
            <div class="tgl-{{ pg }}" style="display:none;">
            <h1>{{ Header }}</h1>
            </div>
        {% endfor %}
    </div>
    <div class="post-content">
        <form id="PillarSurveyForm" action="" class="site-form" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <table>
                <colgroup>
                    <col span="1" width="30%">
                    <col span="1" width="65%">
                    <col span="1" width="5%">
                </colgroup>
                {% for field in form %}
                    <tr class="tgl-{{ field.field.widget.attrs.class }}" style="display:none;">
                        {% if field.field.is_checkbox %}                        
                            <td>{{ field }}</td>                                        
                            <td> {{ field.label|title }} </td>
                        {% else %}
                            <td>{{ field.label_tag|title }}</td>
                            <td> {{ field }} 
                                {% if field.name == "accreditation" and field.url %}
                                    <label for="id_accreditation"><a href="{{ field.url }}" target="_blank">Download Acreditation Certificate &#10515</a></label>
                                {% endif %}                        
                                {% if field.name == "fieldnotes_upload" and qs.fieldnotes_upload.file != none %}
                                    <label id="fieldnotes_link" for="id_fieldnotes_upload"><a href= "{{ qs.fieldnotes_upload.url }}" target="_blank" style="color:blue; cursor: pointer; cursor: hand;"> ...{{ qs.fieldnotes_upload.name|slice:"-50:" }}</a></label>
                                {% endif %} 
                            </td>                            
                        {% endif %}                     
                        <td>
                            {% if field.name == "edm" %}
                                <a href="{% url 'instruments:inst_level_create' %}?next={{request.path}}" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if field.name == "prism" %}
                                <a href="{% url 'instruments:inst_level_create' %}?next={{request.path}}" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if field.name == "level" %}
                                <a href="{% url 'instruments:inst_level_create' %}?next={{request.path}}" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if field.name == "staff" %}
                                <a href="{% url 'instruments:inst_staff_create' %}?next={{request.path}}" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if field.name == "thermometer" %}
                                <a href="{% url 'instruments:inst_level_create' %}?next={{request.path}}" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if field.name == "barometer" %}
                                <a href="{% url 'instruments:inst_level_create' %}?next={{request.path}}" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if field.name == "hygrometer" %}
                                <a href="{% url 'instruments:inst_level_create' %}?next={{request.path}}" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if field.name == "uncertainty_budget" %}
                                <a href="{% url 'baseline_calibration:uc_budget_create' %}"  target="_blank" class="px-2 py-1 add-button bg-blue-300 hover:bg-blue-200">
                                    <span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                        </td>
                    </tr>
                            
                    {% for error in field.errors %}
                    <tr class="tgl-{{ field.field.widget.attrs.class }}" style="display:none;">
                        <td></td>
                        <td>
                            <p style="color:Red;">{{ error }}</p>
                        </td>
                        <td></td>
                    </tr>
                    {% endfor %}
                            
                {% endfor %}
                {% for field in survey_files %}
                    <tr class="tgl-{{ field.field.widget.attrs.class }}" style="display:none;">
                        <td>{{ field.label_tag|title }}</td>
                        <td>
                            {{ field }}
                        </td>
                    </tr>                 
                {% endfor %}
            </table>
            <div class="button-container">
                <button type="button" id="prevBtn" onclick="nextPrev(-1)" class="submit-button bg-green-500 hover:bg-green-400" style="text-align: center"> &#8678; Back</button>
                <a href= "{% url 'baseline_calibration:calibration_home' %}" class="submit-button bg-red-500 hover:bg-green-400" style="text-align: center"> Cancel</a>
                <button type="button" id="nextBtn" onclick="nextPrev(1)" class="submit-button bg-green-500 hover:bg-green-400" >Next &#8680;</button>
            </div>
        </form>
        <div style="margin-left: auto;margin-right: 0;">
            <h4 id=pgOfpgs>1</h4>
        </div>
    </div>
</article>

<script>
// Find Current tab and Last tab
var currentTab = 0;
{% for field in form %}
    {% if field.errors %}
        currentTab = parseInt('{{ field.field.widget.attrs.class }}'.replace('page',''));
    {% endif %}
    {% if forloop.last %}
        const lastTab = parseInt('{{ field.field.widget.attrs.class }}'.replace('page',''));
    {% endif %}
{% endfor %}
showTab(currentTab); // Display the current tab
console.log(lastTab)

function showTab(n) {
  // This function will display the specified tab of the form...
  var x = document.getElementsByClassName("tgl-page"+(n));
  for (var i = 0; i < x.length; i++) {
   x[i].style.display = '';
   }
  
  if (n == 0) {
    document.getElementById("prevBtn").style.display = "none";
  } else {
    document.getElementById("prevBtn").style.display = "inline";
  }
  if (n == lastTab) {
    document.getElementById("nextBtn").innerHTML = "Submit";
  } else {
    document.getElementById("nextBtn").innerHTML = "Next";
  }
  document.getElementById("pgOfpgs").innerHTML = "Page "+ (n+1) + " of " + (lastTab+1);
}

function nextPrev(n) {
  // This function will figure out which tab to display
  var x = document.getElementsByClassName("tgl-page"+(currentTab));
  // Exit the function if any field in the current tab is invalid:
  if (n == 1 && !validateForm()) return false;
  
  for (var i = 0; i < x.length; i++) {
   x[i].style.display = 'none';
   }
  currentTab = currentTab + n;
  
  if (currentTab > lastTab) {
    document.getElementById("PillarSurveyForm").submit();
    return false;
  }
  showTab(currentTab);
}

function validateForm() {
  // This function deals with validation of the form fields
  var y, i, valid = true;
  y = document.getElementsByClassName("page"+(currentTab));

  for (i = y.length-1; i > -1; i--) {
      if (!y[i].checkValidity()) {
        y[i].reportValidity();
        valid = false;
      }
    }

  return valid; // return the valid status
}

function tglEdmFile() {
  // This function will hide/unhide the EDM file select
  var chk = document.getElementById("id_change_edm");
  var slct = document.getElementById("id_edm_file");
  var e = document.getElementsByClassName("tgl-edm_file");
  
  for (var i = 0; i < e.length; i++) {
     if (chk.checked) {
          e[i].style.display = '';
          slct.type = "text";
          slct.type = "file";
      } else {
          e[i].style.display = 'none';
      }
  }
}

function tglLvlFile() {
  // This function will hide/unhide the Level file select
  var chk = document.getElementById("id_change_lvl");
  var slct = document.getElementById("id_lvl_file");
  var e = document.getElementsByClassName("tgl-lvl_file");
  
  for (var i = 0; i < e.length; i++) {
     if (chk.checked) {
          e[i].style.display = '';
          slct.type = "text";
          slct.type = "file";
      } else {
          e[i].style.display = 'none';
      }
  }
}

function ChgNoteFile() {
  var lnk = document.getElementById("fieldnotes_link");
  
  lnk.textContent = '';
}
</script>


{% endblock %}

baseline_calibration/templates/baseline_calibration/edm_rawdata.html
{% extends 'base_generic.html' %}
{% load static %}


{% block content %} 

<article class="post">
	<div class="page-content">
        <div class="text-center">
            <h1>Imported EDM Observations</h1>
        </div>
    <form action="" style="font-size:10.0pt;width:4500px;" class="site-form" method="post" enctype="multipart/form-data">               
        <div class="flexbox-container_IB flexbox-item-left_IB">
        		<p>The pillar survey observations are used to calculate the baselines 'certified distances'<a href= "#"> &#x1F6C8</a>
               and the pillar offsets from the first pillar to last pillar alignment.<a href= "#"> &#x1F6C8</a>
               Please select/deselect the observations in the following table to use for the alignment and/or distance calculations.</p>                 
        </div>  
        <div class="flexbox-container_IB" style="width: 100%;">
        		<div class="flexbox-item_400_IB"><i>* Click the table headers to sort table</i></div> <!-- https://www.amp-what.com/unicode/search/down%20arrow -->
	        	<div class="flexbox-item_IB" style="width: 100%;text-align:right"><a href="#bottom">Scroll to bottom &#128317</a></div>
        </div>
        <div class="flexbox-container_IB flexbox-item_IB" style="min-width: 600px;">
		        {% csrf_token %}
						<table id="obsTable">
		                {{ edm_obs_formset.management_form }}
		                {% for form, raw in formset %}
		                    {% if forloop.first %}
		                    <tr>
			                      <th onclick="sortTable(0)"> Obs # </th>
			                      <th onclick="sortTable(1)"> From Pillar </th>
			                      <th onclick="sortTable(2)"> To Pillar </th>
			                      <th onclick="sortTable(3)"> Instrument Height (m)</th>
			                      <th onclick="sortTable(4)"> Target Height (m)</th>
			                      <th onclick="sortTable(5)"> Hz direction (dd)</th>
			                      <th onclick="sortTable(6)"> Slope Distance (m)</th>
			                      <th onclick="sortTable(7)"> Raw Temperature (°C) </th>
			                      <th onclick="sortTable(8)"> Raw Pressure mBar </th>
			                      <th onclick="sortTable(9)"> Raw Humidity (%) </th>
			                      <th onclick="sortTable(10)"> Select for Alignment Survey </th>
			                      <th onclick="sortTable(11)"> Select for Certified Distances </th>
		                        <td style="display: none;"></td>
		                    </tr>
		                    {% endif %}
		                    <tr>
		                        <td>{{ forloop.counter|stringformat:"03d" }}</td>
		                        <td>{{ raw.from_pillar }}</td>
		                        <td>{{ raw.to_pillar }}</td>
		                        <td>{{ raw.inst_ht|floatformat:3 }}</td>
		                        <td>{{ raw.tgt_ht|floatformat:3 }}</td>
		                        <td>{{ raw.raw_slope_dist|floatformat:4 }}</td>
		                        <td>{{ raw.observed_offset|floatformat:3 }}</td>
		                        <td>{{ raw.raw_temperature|floatformat:1 }}</td>
		                        <td>{{ raw.raw_pressure|floatformat:1 }}</td>
		                        <td>{{ raw.raw_humidity|floatformat:1 }}</td>
		                        <td style="text-align:center">{{ form.use_for_alignment }}</td>
		                        <td style="text-align:center">{{ form.use_for_distance }}</td>
		                        <td style="display: none;">{{ form.id }}</td>
		                    </tr>
		                    {% endfor %}
		      	</table>
      	</div>
        <div class="button-container">
            <a href= "{% url 'baseline_calibration:calibrate1' id=id %}" class="submit-button bg-green-500 hover:bg-green-400" style="text-align: center"> &#8678; Back</button>
            <a href= "{% url 'baseline_calibration:pillar_survey_del' id=id %}" class="submit-button bg-red-500 hover:bg-green-400" style="text-align: center"> Cancel</a>
            <button type="submit" class="submit-button bg-green-500 hover:bg-green-400" >Next &#8680;</button>
        </div>     	
        </form>      
		<div id="bottom" style="margin-left:auto;margin-right:0;text-align:center;">
    		<h4>{{ Page }}</h4>
    </div>   	
	</div>
</article>

<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("obsTable");
  switching = true;
  //Set the sorting direction to ascending:
  dir = "asc"; 
  /*Make a loop that will continue until
  no switching has been done:*/
  while (switching) {
    //start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /*Loop through all table rows (except the
    first, which contains table headers):*/
    for (i = 1; i 
	< (rows.length - 1); i++) {
      //start by saying there should be no switching:
      shouldSwitch = false;
      /*Get the two elements you want to compare,
      one from current row and one from the next:*/
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /*check if the two rows should switch place,
      based on the direction, asc or desc:*/
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch= true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() 
		< y.innerHTML.toLowerCase()) {
          //if so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /*If a switch has been marked, make the switch
      and mark that a switch has been done:*/
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      //Each time a switch is done, increase this count by 1:
      switchcount ++;      
    } else {
      /*If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again.*/
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}
</script>
{% endblock %}

baseline_calibration/templates/baseline_calibration/errors_report.html
{% extends 'base_generic.html' %}
{% load static %}
{% load custom_filter_tags %}


{% block content %} 

<article class="post">
    <div class="post-content">
      {% if messages %}
        <ul class="message-list">
          {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %} </ul>
        <br>
      {% endif %}
    </div>
    <div class="post-content">
        <div class="site-form">
            {% if Check_Errors.Errors|length > 0 %}
                <div class="text-center">
                    <h1><B>Data Errors</B></h1>       
                </div>
                <div class="flexbox-container_IB">
                    <div class="flexbox-item_800_IB flexbox-item-left_IB">                       
                        {% for e in Check_Errors.Errors %}
                            <p>{{e}}</p> 
                        {% endfor %}               
                    </div>
                </div>
            {% endif %}
            
            {% if Check_Errors.Warnings|length > 0 %}
                <h2>Data Warnings</h2>
                <div class="flexbox-container_IB">
                    <div class="flexbox-item_800_IB flexbox-item-left_IB">                       
                        {% for w in Check_Errors.Warnings %}
                            <p>{{forloop.counter}}. {{w}}</p> 
                        {% endfor %}               
                    </div>
                </div>
            {% endif %}
            <div class="button-container">
                <a onclick=history.back() class="submit-button bg-green-500 hover:bg-green-400" style="text-align: center"> &#8678; Back</button>
                <a href= "{% url 'baseline_calibration:calibration_home' %}" class="submit-button bg-red-500 hover:bg-green-400" style="text-align: center"> Cancel</a>
            </div>
        </div>
    </div>
</article>


{% endblock content %}
