calibrationsites/urls.py
from django.urls import path, re_path
from . import views
#from .views import CreateInstrumentWizard   
#
from .forms import CalibrationSiteForm, AddPillarFormSet
# from .forms import ContactForm1, ContactForm2


app_name = 'calibrationsites'

FORMS = [("site_form", CalibrationSiteForm),
        ("pillar_form", AddPillarFormSet),
        ] 
site_creation_wizard = views.CreateCalibrationSiteWizard.as_view(FORMS, 
                            url_name = 'calibrationsites:lstep')

urlpatterns = [
    path('', views.site_home, name = 'home'),

    # path('site-create/', views.site_create, name = 'site-create'),
    path('site/country_create/', views.country_create, name = 'country_create'),
    path('site/state_create/', views.state_create, name = 'state_create'),
    path('site/locality_create/', views.locality_create, name = 'locality_create'),

    re_path(r'^create-site/(?P<step>.+)/$', site_creation_wizard, name='lstep'),
    path('create-site/', site_creation_wizard, name='create-site'),


    # path('create-site/', views.CreateCalibrationSiteWizard.as_view(FORMS), name = 'create-site'),
    # path('site/test/', views.test_view, name = 'test'),
    
    path('site/<int:id>/site_update', views.site_update, name = 'site-update'),
    path('site/<int:id>/pillar_create/', views.pillar_create, name = 'pillar-create'),

    # Detailed view
    path('site/<int:id>/view/', views.site_detailed_view, name = 'site-detail'),
    # path('create-site/', views.CalibrateSiteFormWizard.as_view(), name='create-site'),

    # pillar update
    path('each_pillar_update/<int:id>/<str:pk>', views.each_pillar_update, name = 'each_pillar_update'),
    path('update_pillar/<int:id>', views.PillarUpdateView.as_view(), name = 'update_pillar'),
    # site json
    path('pin-create/get-site-json/<int:site>/', views.get_site_json, name = 'get-site-json'),
    
    # State
    # path('site/get-states-json/<int:country>/', views.get_states_json, name = 'get-states-json'),

    path('get-states-json/<int:country>/', views.get_states_json, name = 'get-states-json'),
    path('get-locality-json/<int:state>/', views.get_locality_json, name = 'get-locality-json'),
]

calibrationsites/forms.py
from django import forms
from django.forms import modelformset_factory
from django.forms.models import BaseFormSet
from .models import (Country, 
					State, 
					Locality, 
					CalibrationSite, 
					Pillar)
from accounts.models import Company

# Prepare forms
class CalibrationSiteForm(forms.ModelForm):
	country = forms.ModelChoiceField(empty_label='--- Choose a Country ---',
									queryset=Country.objects.all(),
									widget=forms.Select())
	state = forms.ModelChoiceField(empty_label='--- Choose a State/Region ---',
									queryset=State.objects.all(),
									widget=forms.Select())
	locality = forms.ModelChoiceField(empty_label='--- Choose a Locality/Suburb ---',
									queryset=Locality.objects.all(),
									widget=forms.Select())
	operator = forms.ModelChoiceField(empty_label='--- Choose your firm/company ---',
									queryset=Company.objects.exclude(company_abbrev='OTH'),
									widget=forms.Select())
	class Meta:
		model = CalibrationSite
		# fields = ['site_type','site_name','site_address','country','state','locality']
		fields = '__all__' 
		widgets = {
				'description': forms.TextInput(attrs={'class': 'text-area'}),
				'site_access' : forms.FileInput(attrs={'accept' : '.pdf'}),
				'site_config' : forms.FileInput(attrs={'accept' : '.pdf'})
			}
	
	# def clean_site_name(self):
	#     return self.cleaned_data.get('site_name')

	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super(CalibrationSiteForm, self).__init__(*args, **kwargs) 
	#     self.fields['operator'].initial = user.company
	#     self.fields['state'].queryset = State.objects.none()
	#     self.fields['locality'].queryset = Locality.objects.none()

	#     if 'country' in self.data:
	#         try:
	#             country_id = int(self.data.get('country'))
	#             self.fields['state'].queryset = State.objects.filter(country_id=country_id).order_by('name')
	#         except (ValueError, TypeError):
	#             pass  # invalid input from the client; ignore and fallback to empty City queryset
	#     elif self.instance.pk:
	#         self.fields['state'].queryset = self.instance.country.state_set.order_by('name')

	#     if 'state' in self.data:
	#         try:
	#             country_id = int(self.data.get('country'))
	#             state_id = int(self.data.get('state'))
	#             self.fields['locality'].queryset = Locality.objects.filter(state__id = state_id, country__id = country_id)
	#         except(ValueError, TypeError):
	#             pass
	#     elif self.instance.pk:
	#         self.fields['locality'].queryset = self.instance.state.locality_set.order_by('name')
#########################################################################
class CalibrationSiteUpdateForm(forms.ModelForm):
	# country = forms.ModelChoiceField(empty_label='Choose a Country',
	#                                 queryset=Country.objects.all(),
	#                                 widget=forms.Select())
	# state = forms.ModelChoiceField(empty_label='Choose a State/Region',
	#                                 queryset=State.objects.all(),
	#                                 widget=forms.Select())
	# locality = forms.ModelChoiceField(empty_label='Choose a Locality/Suburb',
	#                                 queryset=Locality.objects.all(),
	#                                 widget=forms.Select())

	class Meta:
		model = CalibrationSite
		# fields = '__all__' # ('name', 'birthdate', 'country', 'state', 'locality', )
		fields = ['site_type', 'site_name', 'no_of_pillars', 'site_access', 'site_config'] 
		widgets = {
				'site_access' : forms.ClearableFileInput(attrs={'accept' : '.pdf'}),
				'site_config' : forms.ClearableFileInput(attrs={'accept' : '.pdf'})
			}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		# self.fields['state'].queryset = State.objects.none()
		# self.fields['locality'].queryset = Locality.objects.none()
		# disable fields
		self.fields['site_type'].disabled = True

		# if 'country' in self.data:
		#     try:
		#         country_id = int(self.data.get('country'))
		#         self.fields['state'].queryset = State.objects.filter(country_id=country_id).order_by('name')
		#     except (ValueError, TypeError):
		#         pass  # invalid input from the client; ignore and fallback to empty City queryset
		# elif self.instance.pk:
		#     self.fields['state'].queryset = self.instance.country.state_set.order_by('name')

		# if 'state' in self.data:
		#     try:
		#         country_id = int(self.data.get('country'))
		#         state_id = int(self.data.get('state'))
		#         self.fields['locality'].queryset = Locality.objects.filter(state__id = state_id, country__id = country_id)
		#     except(ValueError, TypeError):
		#         pass
		# elif self.instance.pk:
		#     self.fields['locality'].queryset = self.instance.state.locality_set.order_by('name')

#########################################################################
class CountryForm(forms.ModelForm):
	class Meta:
		model = Country
		fields = '__all__'
#########################################################################
class StateForm(forms.ModelForm):
	country = forms.ModelChoiceField(empty_label='--- Choose a Country ---',
									queryset=Country.objects.all(),
									widget=forms.Select())
	class Meta:
		model = State
		fields = '__all__'
#########################################################################
class LocalityForm(forms.ModelForm):
	country = forms.ModelChoiceField(empty_label='--- Choose a Country ---',
									queryset=Country.objects.all(),
									widget=forms.Select())
	state = forms.ModelChoiceField(empty_label='--- Choose a State/Region ---',
									queryset=State.objects.all(),
									widget=forms.Select())
	class Meta:
		model = Locality
		fields = '__all__'
#########################################################################

class PillarForm(forms.ModelForm):
	class Meta:
		model = Pillar
		fields = '__all__'
		exclude = ('id', 'order',)

EditPillarFormSet = modelformset_factory(Pillar, form = PillarForm, 
								extra=0, 
								# max_num=3, 
								can_delete=True)					
#########################################################################
class EditPillarFormSet(EditPillarFormSet):
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		siteid = kwargs.pop('id', None)
		super(EditPillarFormSet, self).__init__(*args, **kwargs) 
		self.queryset = Pillar.objects.filter(site_id__exact = siteid)		
#############################################################################
class AddPillarForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		sitetype = kwargs.pop('sitetype', None)
		sitename = kwargs.pop('sitename', None)
		super(AddPillarForm, self).__init__(*args, **kwargs)
		self.fields['site_id'].queryset = Pillar.objects.filter(site_id__site_name__exact = sitename) 
		self.fields['name'].widget.attrs['required'] = 'required'

	class Meta:
		model = Pillar
		fields = '__all__'
		# exclude = ('site_id', 'order',)

BaseAddPillarFormSet = modelformset_factory(Pillar, form=AddPillarForm, extra=1, can_delete=True)

class AddPillarFormSet(BaseAddPillarFormSet):
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user', None)
		self.sitetype = kwargs.pop('sitetype', None)
		self.sitename = kwargs.pop('sitename', None)
		super(AddPillarFormSet, self).__init__(*args, **kwargs)
		self.queryset = Pillar.objects.filter(site_id__site_name__exact = self.sitename)  
	
	def _construct_form(self, *args, **kwargs):
		# inject user in each form on the formset
		kwargs['user'] = self.user
		kwargs['sitetype'] = self.sitetype
		kwargs['sitename'] = self.sitename
		return super(AddPillarFormSet, self)._construct_form(*args, **kwargs)
###############################################################################

calibrationsites/templates/calibrationsites/CalibrationSiteForm1.html
{% extends 'base_generic.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<article class="post">
    <!-- <div class="post-header mt-10 text-center mb-3">
        <h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
        <p>You can now easily calibrate your Digital Levelling Staves and Electronic Distance Measurements using this web application.</p>
        <p>
            Step {{ wizard.steps.step1 }} of  {{ wizard.steps.count }}
        </p>
    </div> -->
    <div class="post-content">

        <form  class="site-form" action="." method="post" enctype="multipart/form-data">
            <div class="mb-5 site-form-header bg-indigo-300 rounded px-2">
                <h2 class="text-center">Create an new Calibration Site</h2>
            </div>
            <div class="mb-3 px-2 site-form-header">
                <p class="text-center text-lg"><u>Step {{ wizard.steps.step1 }} of  {{ wizard.steps.count }}</u></p>
            </div>
            {% csrf_token %}
            <table>
                {{ wizard.management_form }}
                    {% if wizard.form.forms %}
                        {{ wizard.form.management_form }}
                        {% for form in wizard.form.forms %}
                            <tr>{{ form }}</tr>
                        {% endfor %}
                    {% else %}
                        {% for field in form %}
                            <tr>
                                {% if 'description' in field.name %}
                                    <td width="25%" style="vertical-align:top">{{ field.label_tag }}</td>
                                {% else %}
                                    <td width="25%">{{ field.label_tag }}</td>
                                {% endif %}
                                <td width="65%"> 
                                    {{ field }} 
                                    {% for error in field.errors %}
                                        <p class="error error-danger">{{ error }}</p>
                                    {% endfor %}
                                    {% if not field.field.widget.attrs.placeholder and field.help_text %}
                                        <p class="helptext">{{ field.help_text }}</p>
                                    {% endif %}
                                    {% for error in form.non_field_errors %}
                                        <p class="error error-danger">*** {{ error }} ***</p>
                                        <br>
                                        <br>
                                    {% endfor %}
                                </td>
                                <td width="10%">

                                    {% if 'country' in field.name %}
                                        <a href="/calibrationsites/site/country_create" target="_blank" class="ml-3 px-2 py-1 bg-green-400 border-transparent hover:border-gray-900 rounded text-lg text-white cursor-pointer" onclick="return showAddPopup(this);" id="add_country">&#43;</a>
                                        <!-- <a href="{% url 'calibrationsites:country_create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200" target="__blank"><span class="icon-plus">&#43;</span>Add</a> -->
                                    {% endif %}
                                    {% if 'state' in field.name %}
                                    <a href="/calibrationsites/site/state_create" target="_blank" class="ml-3 px-2 py-1 bg-green-400 border-transparent hover:border-gray-900 rounded text-lg text-white cursor-pointer" onclick="return showAddPopup(this);" id="add_state">&#43;</a>
                                        <!-- <a href="{% url 'calibrationsites:state_create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200" target="__blank"><span class="icon-plus">&#43;</span>Add</a> -->
                                    {% endif %}
                                    {% if 'locality' in field.name %}
                                        <a href="/calibrationsites/site/locality_create" target="_blank" class="ml-3 px-2 py-1 bg-green-400 border-transparent hover:border-gray-900 rounded text-lg text-white cursor-pointer" onclick="return showAddPopup(this);" id="add_locality">&#43;</a>
                                        <!-- <a href="{% url 'calibrationsites:locality_create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200" target="__blank"><span class="icon-plus">&#43;</span>Add</a> -->
                                    {% endif %}
                                        
                                </td>
                            </tr>
                        {% endfor %}
                {% endif %}
            </table>

            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            
            <div class="wizard-button-container">
				{% if wizard.steps.prev %}
					<button class="next-button bg-indigo-400 hover:bg-indigo-300 text-base" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}" formnovalidate> {% trans "<span>&#171;</span> Previous" %}</button>
                    <!-- <button class="next-button bg-green-500 hover:bg-green-300" name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}" formnovalidate>{% trans "First" %}</button> -->
                {% endif %}

				{% if wizard.steps.next %}
					<button class="next-button bg-green-400 hover:bg-green-300 text-base" type="submit">Next <span>&#187;</span></button>
					<a href="{% url 'calibrationsites:home' %}" class="cancelbtn bg-red-500 hover:bg-red-300 text-center">Cancel</a>
				{% else %}
					<button class="next-button bg-green-400 hover:bg-green-300 text-base" type="submit">Submit <span>&#187;</span></button>
					<a href="{% url 'calibrationsites:home' %}" class="cancelbtn bg-red-500 hover:bg-red-300 text-center">Cancel</a>
				{% endif %}
			</div>
        </form>
    </div>
</article>
    <script>
        // Open Pop up
        function showAddPopup(triggeringLink) {
            var name = triggeringLink.id.replace(/^add_/, '');
            href = triggeringLink.href;
            var win = window.open(href, name, "toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=850,width=500,height=400");
            win.focus();
            return false;
        }
        
        // Close Pop up
        function closePopup(win, newID, newRepr) {
            window.sessionStorage.setItem('id_value',  newID);
            win.close();
        }

        const defaultSiteType = document.querySelector('#id_site_form-site_type option[value=""')
        if (defaultSiteType) {
          defaultSiteType.setAttribute('class', 'default');
        }
        const countryInput = document.getElementById('id_site_form-country')
        const defaultCountryText = document.querySelector('#id_site_form-country option[value=""')
      
        if (defaultCountryText) {
            defaultCountryText.setAttribute('class', 'default');
        }
      
        const stateInput = document.getElementById('id_site_form-state')
        const defaultStateText = document.querySelector('#id_site_form-state option[value=""')
    
        if (defaultStateText) {
            defaultStateText.setAttribute('class', 'default');
        }
      
        defaultCountryValue = countryInput.selectedIndex

        // State Select
        countryInput.addEventListener('change', e => {
            countryId = e.target.value;    // get the selected country ID from the HTML input
            var url = `/calibrationsites/get-states-json/${countryId}/`; // set the url of the request with the countryid param
      
            // Set option to empty and fill in with default text
            stateInput.innerHTML = '';
            stateInput.appendChild(defaultStateText)
      
            // Ajax request
            $.ajax({                       // initialize an AJAX request
            type: 'GET',                 // request type
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                  'country': countryId       // add the country id to the GET parameters
            },
            success: function (response) {   // `respose` is the return of the `load_cities` view function
                window.sessionStorage.setItem('countryId',  countryId);
                const stateData = response.data;
                stateData.map(item=> {
                const option = document.createElement('option');
                option.textContent = item.name;
                option.setAttribute('value', item.id)
                stateInput.appendChild(option)
                })
            }
          });
        });
      
        // Locality Select
        const localityInput = document.getElementById('id_site_form-locality')
        const defaultLocalityText = document.querySelector('#id_site_form-locality option[value=""')
      
        if (defaultLocalityText) {
          defaultLocalityText.setAttribute('class', 'default');
        }
      
        stateInput.addEventListener('change', e => {
            stateId = e.target.value;    // get the selected country ID from the HTML input
            var url = `/calibrationsites/get-locality-json/${stateId}/`; // set the url of the request with the countryid param
      
            // Set option to empty and fill in with default text
            localityInput.innerHTML = '';
            localityInput.appendChild(defaultLocalityText)
      
            // Ajax request
            $.ajax({                       // initialize an AJAX request
            type: 'GET',                 // request type
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                  'state': stateId       // add the country id to the GET parameters
            },
            success: function (response) {   // `respose` is the return of the `load_cities` view function
                window.sessionStorage.setItem('stateId',  stateId);
                const localityData = response.data;
                localityData.map(item=> {
                const option = document.createElement('option');
                option.textContent = item.name;
                option.setAttribute('value', item.id)
                localityInput.appendChild(option)
                })
            }
          });
        });
      
        // const log = console.log;
        const defaultCompanyText = document.querySelector('#id_site_form-operator option[value=""')
          if (defaultCompanyText) {
              defaultCompanyText.setAttribute('class', 'default');
          }

        // Store Cookie
        countryItem = window.sessionStorage.getItem('countryId');
        if (countryItem) {
            countryInput.selectedIndex = countryItem;
        }

        stateItem = window.sessionStorage.getItem('stateId');
        if (stateItem) {
            stateInput.selectedIndex = stateItem;
        }

        window.sessionStorage.clear();
      
      </script>
{% endblock %}

calibrationsites/templates/calibrationsites/calibrationsite_update_form.html
{% extends 'base_generic.html' %}
{% load static %}


{% block content %}

<article class="post">
    {% if messages %}
		<ul class="alert messages">
		    {% for message in messages %}
		    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		    {% endfor %}
		</ul>
		<br>
	{% endif %}	

    <div class="post-header mt-12 mb-5">
        <h1 class="post-title">Update the Calibration Site details here.</h1>
    </div>

    <div class="post-content">
      <form action="" class="site-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <table>
          <colgroup>
              <col span="1" width="20%">
              <col span="1" width="70%">
              <!-- <col span="1" width="10%"> -->
          </colgroup>
          </tr>
          {% for field in form %}
            <tr>
              <td>{{ field.label_tag }}</td> 
              <td> 
                  {{ field }} 
                  <!-- Errors -->
                  {% for error in field.errors %}
                      <p class="error error-danger">{{ error }}</p>
                  {% endfor %}
                  <!-- Help text -->
                  {% if not field.field.widget.attrs.placeholder and field.help_text %}
                      <p class="helptext">{{ field.help_text }}</p>
                  {% endif %}
              </td>
              <!-- <td>
                {% if 'country' in field.name %}
                    <a href="{% url 'calibrationsites:country-create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200"><span class="icon-plus">&#43;</span>Add</a>
                {% endif %}
                {% if 'state' in field.name %}
                    <a href="{% url 'calibrationsites:state-create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200"><span class="icon-plus">&#43;</span>Add</a>
                {% endif %}
                {% if 'locality' in field.name %}
                    <a href="{% url 'calibrationsites:locality-create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200"><span class="icon-plus">&#43;</span>Add</a>
                {% endif %}

              </td> -->
          </tr>   
          {% endfor %}

        </table>

          <div class="button-container">
            <button class="save-button bg-green-500 hover:bg-green-400" type="submit" >Update</button>
            <span> <a href="{% url 'calibrationsites:home' %}" class="text-blue-500">Cancel</a></span>
        </div>

      </form>
    </div>
</article>

  <script src="{% static 'calibrationsites/calibration_site.js' %}"></script>
  <!-- <script>
    document.getElementById('id_site_type').disabled = true;
    document.getElementById('id_site_name').disabled = true;
    document.getElementById('id_site_address').disabled = true;
    document.getElementById('id_country').disabled = true;
    document.getElementById('id_state').disabled = true;
    document.getElementById('id_locality').disabled = true;
    document.getElementById('id_operator').disabled = true;
    document.getElementById('id_site_type').disabled = true;
  </script> -->
  
{% endblock %}

calibrationsites/templates/calibrationsites/locality_form.html
{% extends 'base_popup.html' %}
{% load static %}


{% block content %} 

<article class="post">
    <!-- <div class="post-header mt-12 text-center mb-3">
        <h1>Welcome to Landgate's Survey Instrument Calibration website.</h1>
        <p> This form allows to register (or modify) a new (or an existing) calibration site - both Barcode Calibration Range or an EDM Baseline.</p>
    </div> -->

    <div class="post-content">

        <form action="" class="site-form" method="post" enctype="multipart/form-data">
            <div class="mb-5 site-form-header bg-red-200 rounded px-2">
                <h2 class="text-center">Create a Locality</h2>
            </div>

            {% csrf_token %}
            <table>               
                {% for field in form %}
                    <tr>
                        <td width="20%">{{ field.label_tag }}</td> 
                        <td width="75%"> 
                            {{ field }} 
                            <!-- Errors -->
                            {% for error in field.errors %}
                                <p class="error error-danger">{{ error }}</p>
                            {% endfor %}
                            <!-- Help text -->
                            {% if not field.field.widget.attrs.placeholder and field.help_text %}
                                <p class="helptext">{{ field.help_text }}</p>
                            {% endif %}
                        </td>
                        <td width="5%">
                            <!-- {% if 'country' in field.name %}
                                <a href="{% url 'calibrationsites:country_create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200"><span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if 'state' in field.name %}
                                <a href="{% url 'calibrationsites:state_create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200"><span class="icon-plus">&#43;</span>Add</a>
                            {% endif %}
                            {% if 'locality' in field.name %}
                                <a href="{% url 'calibrationsites:locality_create' %}?next={{request.path}}" class="px-3 py-2 add-button bg-blue-200"><span class="icon-plus">&#43;</span>Add</a>
                            {% endif %} -->
        
                        </td>
                    </tr>        
                    
                {% endfor %}
            </table>
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <div class="button-container">
                <button class="submit-button bg-green-500 hover:bg-green-400" type="submit" >Submit</button>
            </div>

        </form>
        
    </div>
</article>

<script>
    const countryInput = document.getElementById('id_country')
    const defaultCountryText = document.querySelector('#id_country option[value=""')

    if (defaultCountryText) {
        defaultCountryText.setAttribute('class', 'default');
        defaultCountryText.setAttribute('value', '');
    }

    const stateInput = document.getElementById('id_state')
    const defaultStateText = document.querySelector('#id_state option[value=""')

    if (defaultStateText) {
        defaultStateText.setAttribute('class', 'default');
        defaultStateText.setAttribute('value', '');
    }

    countryInput.addEventListener('change', e => {
        
        countryId = e.target.value;    // get the selected country ID from the HTML input
        var url = `/calibrationsites/get-states-json/${countryId}/`; // set the url of the request with the countryid param
        console.log(url)
        // Set option to empty and fill in with default text
        stateInput.innerHTML = '';
        stateInput.appendChild(defaultStateText)
        if (countryId) {
            // Ajax request
            $.ajax({                       // initialize an AJAX request
                type: 'GET',                 // request type
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                    'country': countryId       // add the country id to the GET parameters
                },
                success: function (response) {   // `respose` is the return of the `load_cities` view function
                    // console.log(response.data)
                    const stateData = response.data;
                    stateData.map(item=> {
                    const option = document.createElement('option');
                    option.textContent = item.name;
                    option.setAttribute('value', item.id)
                    stateInput.appendChild(option)
                    })
                },
                error: function(error) {
                    console.log(error)
                },
            });
        }
    });

    function refreshParent() 
        {
            window.opener.location.reload(true);
        }
</script>

<body onunload="javascript:refreshParent()">

{% endblock %}